In [11]:
import numpy as np

In [12]:
#problem 1- to store {steps before 7pm along with days} -[steps,daynumber]
steps_walked = np. array([[6012, 1], [7079, 2], [6886, 3], [7230, 4], [4598, 5], [5564, 6], [6971, 7], [7763, 8], [8032, 9], [9569, 10]])
print(steps_walked)

[[6012    1]
 [7079    2]
 [6886    3]
 [7230    4]
 [4598    5]
 [5564    6]
 [6971    7]
 [7763    8]
 [8032    9]
 [9569   10]]


In [40]:
#problem 2 -[as battery dies at 7, he walks on an average of 2000 steps after 7, so we add 2000 steps to the existing one]
new_steps = steps_walked[:,0] + np.array([2000])
print(new_steps)


[ 8012  9079  8886  9230  6598  7564  8971  9763 10032 11569]


In [41]:
#problem 3 - to consider the index of the steps above 9000 steps after adding 2000 and storing in limit index
limit_index = np.where(new_steps > 9000)
print(new_steps[limit_index])

[ 9079  9230  9763 10032 11569]


In [42]:
#problem 4 - printing the elements in an order
print(np.sort(new_steps[limit_index]))

[ 9079  9230  9763 10032 11569]
