In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3])

In [4]:
a

array([1, 2, 3])

In [13]:
a=np.array(10)
b=np.array([1,2,3])
c=np.array([[3,4,5],[6,7,8]])
d=np.array([[[1.2,3],[4,5,6]], [[1,2,3], [4,5,6]]])

In [14]:
print('a dimension:',a.ndim)
print('b dimension:',b.ndim)
print('c dimension:',c.ndim)
print('d dimension:',d.ndim)

a dimension: 0
b dimension: 1
c dimension: 2
d dimension: 3


In [15]:
print(a)
print('shape of a:',a.shape)
print(b)
print('shape of b:',b.shape)
print(c)
print('shape of c:',c.shape)
print(d)
print('shape of d:',d.shape)


10
shape of a: ()
[1 2 3]
shape of b: (3,)
[[3 4 5]
 [6 7 8]]
shape of c: (2, 3)
[[[3 6 7]
  [7 8 9]]

 [[1 2 3]
  [9 8 7]]]
shape of d: (2, 2, 3)


In [16]:
print(c.dtype)
print(d.dtype)

int32
int32


In [17]:
len(b)

3

In [18]:
print(type(a))
print(type(a))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [19]:
len(b)

3

In [22]:
k1=[100,200,300]
k2=[78,90,45]
k3=np.array(k1)
k4=np.array(k2)
print(type(k3))
print(k3)

<class 'numpy.ndarray'>
[100 200 300]


In [24]:
np.arange(1,56)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55])

In [25]:
np.arange(0,5,2)

array([0, 2, 4])

In [29]:
np.eye(9,dtype =int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [30]:
np.zeros((4,6),dtype=int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [31]:
np.ones((4,6),dtype=int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [32]:
np.full((6,8),20)

array([[20, 20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20]])

In [33]:
x=[1,2,3,4,5]
np.diag(x)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [34]:
np.random.randn(2,10)

array([[ 0.88821026, -0.19176215, -0.22423317,  1.32729716, -1.3176381 ,
        -0.53362587,  0.26469913, -0.76675221,  0.50948539,  0.51400971],
       [-0.42898594, -0.24444034, -0.97393915, -0.3229069 , -2.26124507,
         0.69311504,  0.34668896, -0.99883647,  1.73286615,  1.12865502]])

In [37]:
np.random.random(1)[0]

0.9125151512108652

In [41]:
x=np.arange(1,21)
print(x)
print(x.shape)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
(20,)


In [42]:
o=x.reshape(10,2)
print(o)
print(o.shape)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]
(10, 2)


In [44]:
k=x.reshape(5,4)
print(k)
print(o.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
(10, 2)


In [45]:
i=x.reshape(1,10,2)
print(i)
print(i.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]
  [11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]]]
(1, 10, 2)


In [46]:
v=x.ravel()
print(v.shape)
print(v)

(20,)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [52]:
print(x)
x10.reshape((2,10),order='F')

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20]])

In [102]:
x10.flatten()


array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [120]:
a

array([[list([1, 2, 3]), list([2, 4.7])],
       [list([7, 9, 0]), list([10, 11, 15])]], dtype=object)

In [113]:
x1=np.arange(10)
x1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
x2=x1

In [71]:
print(x1)
print(x2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [74]:
x2[0]=10

In [75]:
print(x1)
print(x2)

[10  1  2  3  4  5  6  7  8  9]
[10  1  2  3  4  5  6  7  8  9]


In [77]:
print(np.shares_memory(x1,x2))
print(id(x1))
print(id(x2))

True
1953981637904
1953981637904


In [80]:
x3=x1.view()

In [81]:
np.shares_memory(x1,x3)

True

In [87]:
x3[0]=0

In [88]:
print(x1)
print(x3)

[  0   1   2   3   4 100   6   7   8   9]
[  0   1   2   3   4 100   6   7   8   9]


In [90]:
x4=np.copy(x1)

In [92]:
x4[-1]=10

In [93]:
print(x1)
print(x4)

[  0   1   2   3   4 100   6   7   8   9]
[  0   1   2   3   4 100   6   7   8  10]


In [109]:
print(id(x1))
print(id(x4))
np.shares_memory(x1,x4)

In [111]:
print(a)

[[list([1, 2, 3]) list([2, 4.7])]
 [list([7, 9, 0]) list([10, 11, 15])]]


In [123]:
a =10


In [125]:
 a

10

In [126]:
a>3

True

In [129]:
x1 == x4

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
       False])

# a=[1,2,3]
#b=[1,4,8]

In [131]:
print(x1)
print(x4)
np.vstack((x1,x4))

[0 1 2 3 4 5 6 7 8 9]
[  0   1   2   3   4 100   6   7   8  10]


array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [  0,   1,   2,   3,   4, 100,   6,   7,   8,  10]])

In [132]:
np.hstack((x1,x4))

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,   0,   1,   2,
         3,   4, 100,   6,   7,   8,  10])

In [ ]:
insert

In [133]:
print(x1)
print(x4)
np.insert(x1,5,x4)


[0 1 2 3 4 5 6 7 8 9]
[  0   1   2   3   4 100   6   7   8  10]


array([  0,   1,   2,   3,   4,   0,   1,   2,   3,   4, 100,   6,   7,
         8,  10,   5,   6,   7,   8,   9])

In [134]:
print(x2)
np.delete(x2,0)

[  0   1   2   3   4 100   6   7   8   9]


array([  1,   2,   3,   4, 100,   6,   7,   8,   9])

In [ ]:
mathsmatical


In [135]:
a=np.array([[4,6,7],[2,9,0],[6,4,2]])

In [136]:
np.sin(a)

array([[-0.7568025 , -0.2794155 ,  0.6569866 ],
       [ 0.90929743,  0.41211849,  0.        ],
       [-0.2794155 , -0.7568025 ,  0.90929743]])

In [137]:
np.cos(a)

array([[-0.65364362,  0.96017029,  0.75390225],
       [-0.41614684, -0.91113026,  1.        ],
       [ 0.96017029, -0.65364362, -0.41614684]])

In [138]:
np.sum(a)

40

In [139]:
np.median(a)

4.0

In [140]:
np.mean(a)

4.444444444444445

In [141]:
np.std(a)

2.671292284482513

In [142]:
np.max(a)

9

In [143]:
np.sort(a)

array([[4, 6, 7],
       [0, 2, 9],
       [2, 4, 6]])

In [144]:
m=np.where(x1==4)
m

(array([4], dtype=int64),)

In [145]:
x1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [146]:
np.where(x1%2==0)

(array([0, 2, 4, 6, 8], dtype=int64),)

In [147]:
np.where(x1>5,x1,0)

array([0, 0, 0, 0, 0, 0, 6, 7, 8, 9])

In [148]:
print(dir(list))

['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']
